// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models;

[Table("blog_post_tag")]
[Index("PostId", Name = "FK_blog_post_tag_blog_post")]
[Index("TagId", Name = "FK_blog_post_tag_tag")]
public partial class BlogPostTag
{
    [Key]
    [Column("id", TypeName = "bigint(20)")]
    public long Id { get; set; }

    [Column("post_id", TypeName = "bigint(20)")]
    public long PostId { get; set; }

    [Column("tag_id", TypeName = "bigint(20)")]
    public long TagId { get; set; }

    [ForeignKey("PostId")]
    [InverseProperty("BlogPostTags")]
    public virtual BlogPost Post { get; set; }

    [ForeignKey("TagId")]
    [InverseProperty("BlogPostTags")]
    public virtual Tag Tag { get; set; }
}