// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models;

[Table("experience_tag")]
[Index("ExperienceId", Name = "FK__experience")]
[Index("TagId", Name = "FK__tag")]
public partial class ExperienceTag
{
    [Key]
    [Column("id", TypeName = "bigint(20)")]
    public long Id { get; set; }

    [Column("experience_id", TypeName = "bigint(20)")]
    public long ExperienceId { get; set; }

    [Column("tag_id", TypeName = "bigint(20)")]
    public long TagId { get; set; }

    [ForeignKey("ExperienceId")]
    [InverseProperty("ExperienceTags")]
    public virtual Experience Experience { get; set; }

    [ForeignKey("TagId")]
    [InverseProperty("ExperienceTags")]
    public virtual Tag Tag { get; set; }
}