// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models;

[Table("project_tag")]
[Index("ProjectId", Name = "FK_project_tag_project")]
[Index("TagId", Name = "FK_project_tag_tag")]
public partial class ProjectTag
{
    [Key]
    [Column("id", TypeName = "bigint(20)")]
    public long Id { get; set; }

    [Column("project_id", TypeName = "bigint(20)")]
    public long ProjectId { get; set; }

    [Column("tag_id", TypeName = "bigint(20)")]
    public long TagId { get; set; }

    [ForeignKey("ProjectId")]
    [InverseProperty("ProjectTags")]
    public virtual Project Project { get; set; }

    [ForeignKey("TagId")]
    [InverseProperty("ProjectTags")]
    public virtual Tag Tag { get; set; }
}