// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models;

[Table("tag")]
public partial class Tag
{
    [Key]
    [Column("id", TypeName = "bigint(20)")]
    public long Id { get; set; }

    [Required]
    [Column("name")]
    [StringLength(50)]
    public string Name { get; set; }

    [InverseProperty("Tag")]
    public virtual ICollection<BlogPostTag> BlogPostTags { get; set; } = new List<BlogPostTag>();

    [InverseProperty("Tag")]
    public virtual ICollection<ExperienceTag> ExperienceTags { get; set; } = new List<ExperienceTag>();

    [InverseProperty("Tag")]
    public virtual ICollection<ProjectTag> ProjectTags { get; set; } = new List<ProjectTag>();
}